{% set prefix = "spacy-model-" %}
{% set name = "en_core_web_" %}
{% set version = "3.2.0" %}
{% set build_number = 0 %}
# see https://github.com/explosion/spacy-models/blob/master/compatibility.json
# but the pattern _generally_ seems to be x.x
{% set spacy_version = ".".join(version.split(".")[:2] + ['*']) %}

package:
  name: {{ prefix }}{{ name[:-1] }}
  version: {{ version }}

source:
  - url: https://github.com/explosion/spacy-models/releases/download/{{ name }}sm-{{ version }}/{{ name }}sm-{{ version }}.tar.gz
    sha256: f884c5958019509db28f9a3a3bb2944c5a7a094eb28e61e8a9d9fdfa40f549f4
    folder: sm
  - url: https://github.com/explosion/spacy-models/releases/download/{{ name }}md-{{ version }}/{{ name }}md-{{ version }}.tar.gz
    sha256: efced3da7aa5f76a1308c9ad48ca95e09480cf5a5c9c26f5d08160c0ff0e00ab
    folder: md
  - url: https://github.com/explosion/spacy-models/releases/download/{{ name }}lg-{{ version }}/{{ name }}lg-{{ version }}.tar.gz
    sha256: 40bab7d231a67a17cdac169bdf3a18070d34e941302bc037841b5361d95b89f3
    folder: lg
  - url: https://github.com/explosion/spacy-models/releases/download/{{ name }}trf-{{ version }}/{{ name }}trf-{{ version }}.tar.gz
    sha256: f2296d93d63c228f7b4df2a29f23f1e9fe291180c7257ed3cb7221c4e4ae30e3
    folder: trf
  - url: https://raw.githubusercontent.com/explosion/spaCy/master/LICENSE
    sha256: b90775797175e7aa165a5508c8132da463b8ae029b419f4fc52450276d9f2872

build:
  noarch: python
  number: {{ build_number }}

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - setuptools
    - python >=3.6

test:
  commands:
    - echo "make lint happy"

outputs:
  - name: {{ prefix }}{{ name }}sm
    files:
      - sm
      - LICENSE
    build:
      noarch: python
      number: {{ build_number }}
      script: cd sm && {{ PYTHON }} -m pip install . --no-deps -vv
    requirements:
      host:
        - python >=3.6
        - pip
      run:
        - python >=3.6
        - setuptools
        - spacy =={{ spacy_version }}
    test:
      imports:
        - {{ name }}sm
      requires:
        - spacy
      commands:
        - python -c "__import__('{{ name }}sm').load()"
        - python -c "__import__('spacy').load('{{ name }}sm')"

  - name: {{ prefix }}{{ name }}md
    files:
      - md
      - LICENSE
    build:
      noarch: python
      number: {{ build_number }}
      script: cd md && {{ PYTHON }} -m pip install . --no-deps -vv
    requirements:
      host:
        - python >=3.6
        - pip
      run:
        - python >=3.6
        - setuptools
        - spacy =={{ spacy_version }}
    test:
      imports:
        - {{ name }}md
      requires:
        - spacy
      commands:
        - python -c "__import__('{{ name }}md').load()"
        - python -c "__import__('spacy').load('{{ name }}md')"

  - name: {{ prefix }}{{ name }}lg
    files:
      - lg
      - LICENSE
    build:
      noarch: python
      number: {{ build_number }}
      script: cd lg && {{ PYTHON }} -m pip install . --no-deps -vv
    requirements:
      host:
        - python >=3.6
        - pip
      run:
        - python >=3.6
        - setuptools
        - spacy =={{ spacy_version }}
    test:
      imports:
        - {{ name }}lg
      requires:
        - spacy
      commands:
        - python -c "__import__('{{ name }}lg').load()"
        - python -c "__import__('spacy').load('{{ name }}lg')"

  - name: {{ prefix }}{{ name }}trf
    files:
      - trf
      - LICENSE
    build:
      noarch: python
      number: {{ build_number }}
      script: cd trf && {{ PYTHON }} -m pip install . --no-deps -vv
    requirements:
      host:
        - python >=3.6
        - pip
      run:
        - python >=3.6
        - setuptools
        - spacy =={{ spacy_version }}
        - spacy-alignments
        - spacy-transformers
    test:
      imports:
        - {{ name }}trf
      requires:
        - spacy
      commands:
        - python -c "__import__('{{ name }}trf').load()"
        - python -c "__import__('spacy').load('{{ name }}trf')"
about:
  home: https://spacy.io
  license: MIT
  license_file: LICENSE
  summary: English multi-task CNN trained on OntoNotes, with GloVe vectors trained on Common Crawl.
  doc_url: https://spacy.io/models/en
  dev_url: https://github.com/explosion/spacy-models

extra:
  recipe-maintainers:
    - sodre
    - bollwyvl
    - setu4993
