{% set prefix = "spacy-model-" %}
{% set name = "en_core_web_" %}
{% set version = "2.3.0" %}

package:
  name: {{ prefix|lower }}{{ name[:-1]|lower }}
  version: {{ version }}

source:
  - url: https://github.com/explosion/spacy-models/releases/download/{{ name }}sm-{{ version }}/{{ name }}sm-{{ version }}.tar.gz
    sha256: ea8c87848b4a97ced174919e08c00c7888a30495ace38d281d455ee270da2c12
    folder: sm
  - url: https://github.com/explosion/spacy-models/releases/download/{{ name }}md-{{ version }}/{{ name }}md-{{ version }}.tar.gz
    sha256: 70a957e8cf71f3d98b387d3ddb91a19b1ec016c26b2e580daee1aa0827d648fb
    folder: md
  - url: https://github.com/explosion/spacy-models/releases/download/{{ name }}lg-{{ version }}/{{ name }}lg-{{ version }}.tar.gz
    sha256: c2c532aad85495bd5708ec077ceb3700794cd64b88480f654942f9303e2fca55
    folder: lg
  - url: https://raw.githubusercontent.com/explosion/spaCy/master/LICENSE
    sha256: 2946c76df2417fe4e29c693e4d877f8516630740f0ede219edf1b0d06c61d536

build:
  noarch: python
  number: 0

requirements:
  host:
    - python
    - pip
  run:
    - setuptools
    - python

test:
  commands:
    - echo "make lint happy"

outputs:
  - name: {{ prefix }}{{ name }}sm
    files:
      - sm
      - LICENSE
    build:
      noarch: python
      number: 0
      script: cd sm && {{ PYTHON }} -m pip install . --no-deps -vv
    requirements:
      host:
        - python
        - pip
      run:
        - python
        - setuptools
    test:
      imports:
        - {{ name }}sm
      requires:
        - spacy {{ version.split('.')[0] }}.{{ version.split('.')[1] }}.*
      commands:
        - python -c "__import__('{{ name }}sm').load()"
        - python -c "__import__('spacy').load('{{ name }}sm')"
  - name: {{ prefix }}{{ name }}md
    files:
      - md
      - LICENSE
    build:
      noarch: python
      number: 0
      script: cd md && {{ PYTHON }} -m pip install . --no-deps -vv
    requirements:
      host:
        - python
        - pip
      run:
        - python
        - setuptools
    test:
      imports:
        - {{ name }}md
      requires:
        - spacy {{ version.split('.')[0] }}.{{ version.split('.')[1] }}.*
      commands:
        - python -c "__import__('{{ name }}md').load()"
        - python -c "__import__('spacy').load('{{ name }}md')"
  - name: {{ prefix }}{{ name }}lg
    files:
      - lg
      - LICENSE
    build:
      noarch: python
      number: 0
      script: cd lg && {{ PYTHON }} -m pip install . --no-deps -vv
    requirements:
      host:
        - python
        - pip
      run:
        - python
        - setuptools
    test:
      imports:
        - {{ name }}lg
      requires:
        - spacy {{ version.split('.')[0] }}.{{ version.split('.')[1] }}.*
      commands:
        - python -c "__import__('{{ name }}lg').load()"
        - python -c "__import__('spacy').load('{{ name }}lg')"

about:
  home: https://spacy.io
  license: MIT
  license_file: LICENSE
  summary: English multi-task CNN trained on OntoNotes, with GloVe vectors trained on Common Crawl.
  doc_url: https://spacy.io/models/en
  dev_url: https://github.com/explosion/spacy-models

extra:
  recipe-maintainers:
    - sodre
    - bollwyvl
    - setu4993
